---
title: "Comparative DVN anatomy mus aco"
author: "Justin Varholick"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggthemr)
library(ggsci)
library(tidyverse)
library(readxl)
library(TOSTER)
library(cowplot)
library(ggbeeswarm)
```

#Import data and organize
```{r}
acomusdvn <- read_xlsx("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axon counts Aco Mus/AcoMusAxonComparison_data.xlsx")
head(acomusdvn)
```

#graphs
```{r}
graph1 <- ggplot(acomusdvn, aes(NumberPosition, count, shape=Species, color=LetterPosition))+
  geom_quasirandom(size=3)+
  scale_x_continuous(breaks=c(1,2,3,4,5,6))+
  theme_cowplot()
graph1

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axon counts Aco Mus/scatter_AcoMusAxonCount.png", graph1, units="cm", width = 19, height = 8, device='png', dpi=300)
```
```{r}
graph2 <- ggplot(acomusdvn, aes(NumberPosition, count, shape=Species, color=LetterPosition))+
  geom_quasirandom(size=3)+
  scale_x_continuous(breaks=c(1,2,3,4,5,6))+
  ylab("DVN Axon Count")+
  theme_cowplot()+
  facet_wrap(~Species)
graph2

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axon counts Aco Mus/scatter_AcoMusAxonCount_facet.png", graph2, units="cm", width = 19, height = 8, device='png', dpi=300)
```
```{r}
graph3 <- ggplot(acomusdvn, aes(Species, count, size=NumberPosition, color=LetterPosition))+
  geom_quasirandom(alpha=0.75)+
  stat_summary(fun=median, geom="crossbar", size=0.5, width=0.25)+
  ylab("DVN Axon Count")+
  theme_cowplot()
graph3

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axon counts Aco Mus/scatter_AcoMusAxonCount_species.png", graph3, units="cm", width = 19, height = 10, device='png', dpi=300)
```

