---
title: "Whikser regeneration, axon counts"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggthemr)
library(ggsci)
library(tidyverse)
library(readxl)
library(TOSTER)
library(cowplot)
```

#Import data and organize
```{r}
Aconinetydpi <- read_xls("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axont counts 90dpi/aco_90dpi_march.xls")
str(Aconinetydpi)
Aconinetydpi$animalid <- as.factor(Aconinetydpi$animalid)
head(Aconinetydpi)

Aconinetydpi <- mutate(Aconinetydpi, whiskerid=paste(animalid, whiskerid2, sep="_"))

```
#Plot that data
```{r}
Aconinetydpi$injury <- factor(Aconinetydpi$injury, levels=c("ctrl", "wnd"))

figure1 <- ggplot(Aconinetydpi, aes(injury, `axon count`)) +
  geom_boxplot(aes(fill=injury), size=1)+
  geom_line(aes(group=whiskerid), size=0.5) +
  geom_point(size =2)+
  scale_fill_npg()+
  ylab("axon count in DVN") + xlab("")+
  scale_x_discrete(labels=c("ctrl whiskers", "90dpi whiskers"))+
  scale_y_continuous(limits = c(0,250), expand=c(0,0))+
  guides(color="none", fill="none")+
  theme_cowplot()

figure1

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysWhiskerRegeneration/Axont counts 90dpi/boxplot_90dpiaxoncount.png", figure1, units="cm", width = 19, height = 22, device='png', dpi=300)
```



